### ISSUE TITLE
각 컴포넌트의 재사용성이 높나요?

### ISSUE THREAD

**Issue by sonshineLiveinEarth** [sonshineLiveinEarth/MagazineProject#1]
안녕하세요, 안지현 매니저님!

이번 프로젝트에서 컴포넌트를 잘 쪼갰는지 궁금합니다.

포스팅 생성 시, 유저가 선택할 수 있는 레이아웃이 3가지이기 때문에 컴포넌트를 각각 만들고 디테일페이지와 수정페이지도 레이아웃 a, b ,c 유형별로 쪼갰습니다. 그러다보니 아래와 같이 게시물 관련한 컴포넌트가 총 9개 파일이 생성됐습니다.

메인페이지(Main.js)에 삽입되는 (PostingCard.js)에 들어가는 컴포넌트
-PostCardA.js
-PostCardB.js
-PostCardC.js

게시물 클릭 시 해당 게시물의 상세페이지 컴포넌트
-DetailA.js
-DetailB.js
-DetailC.js

위 게시물 상세페이지에서 수정하기 클릭 시 나타나는 컴포넌트
-ModifiA.js
-ModifiB.js
-ModifiC.js

1. 컴포넌트를 쪼개놓으니 파일별 가독성은 높아졌지만 **큰 틀의 레이아웃은 거의 동일하고, 
각 페이지에서 필요한 기능 부분만 수정되다보니 겹치는 코드가 많아서** 작업하면서 확신이 잘 서지 않았는데, 의견 주시면 감사하겠습니다.

2. 특히 스타일컴포넌트의 경우, 전역으로 사용하는 `createGlobalStyle` 을 사용해보고 싶었으나 
div 나 body 와 같은 html 태그에 스타일을 넣던데 div가 굉장히 여러 개 쓰이는데 원하는 변수명으로
전역 스타일컴포넌트를 지정할 수 있을지도 궁금합니다.

**Comment by jihyunan-dev** [comment]
안녕하세요 윤주님:) 질문에 대해 답변드리겠습니다. 

1. 먼저 생각하신것처럼 더 효율적인 방법은 있을겁니다. 하지만 지금하신 방법을 거쳐야 비로소 더 효율적으로 정리하실 수 있을 것이기 때문에 충분히 잘 쪼개놓으셨다고 우선 말씀드리고 싶습니다.
 - 1) 먼저 각 컴포넌트 A, B, C에는 윤주님이 작성하신 `styled component`들이 존재합니다. 각 스타일 컴포넌트들은 이름도 비슷하고 내용도 같은 경우들이 많습니다. 그렇다면 우선 이 스타일 컴포넌트는 하나만 만들어서 `import`하여 여러곳에서 사용하는 방법이 있어 보입니다.
 - 2) 하나의 컴포넌트가 크지도 않고, 위치 자체도 겹치지 않는다고하면 제 경우는 큰 틀은 별도의 컴포넌트가 있고, 바뀌는 부분만 컴포넌트를 3개로 쪼갤 것 같습니다. 
 그러면 파일이 4개가 될 거라고 생각하시겠죠? 물론 4개로 만들어도 큰 문제는 없다고 생각합니다. 하지만 하나의 파일 안에서도 여러개의 컴포넌트를 만들 수 있습니다.
 제가 사용하는 방식 중 하나는 다음과 같습니다. 정답은 절대 아니며, 이런 식으로 만들 수도 있다는 생각만 해주시고 윤주님이 편한 방법을 고민해보시면 좋겠습니다:)
 ```javascript
 const PostCard = ({layoutType}) => {
   const getLayout = () => {
     switch(layoutType) {
       case 'layoutA':
         return <LayoutA />
       case 'layoutB':
         return <LayoutB />
       case 'layoutC':
         return <LayoutC />
     }
   }
 
   return (
     <Container>
       <PostHeader />
         {getLayout()}
       <PostFooter />
     </Container>
   )
 }
 
 const LayoutA = () => {
   return (<></>)
 }
 
 const LayoutB = () => {
   return (<></>)
 }
 
 const LayoutC = () => {
   return (<></>)
 }

 ```
 
 2. `globalStyle`의 경우 정말 모든 곳에서 공통적으로 사용될 것으로 예상되는 내용만 넣으시는 것이 좋습니다:) 
 그럼 똑같이 생긴 버튼 A, B, C가 있다면 어떻게하면 될까요?
 1) style까지 적용된 버튼 컴포넌트를 각각 만들어서 `import`해서 사용하시면 됩니다:)
 2) `styled-components`의 `css`를 활용하시는 방법도 있을 것 같습니다. (https://styled-components.com/docs/api#css) 
 사용방법 : https://swtpumpkin.github.io/frontend/react/styledComponentsCss/
