### ISSUE TITLE
게시물 작성페이지, 수정페이지에서 새로고침하면 빈화면이 되는 이슈

### ISSUE THREAD

**Issue by sonshineLiveinEarth** [sonshineLiveinEarth/MagazineProject#2]
추가로 질문 한가지 더 여쭤봅니다!
현재 로그인되어 있는 유저(`auth.currentUser`)의 email과 같은 email을 가지고 있는
유저 db를 불러오는 코드를 아래와 같이 작성했습니다.

```
// Write.js

import { collection, query, where, getDocs } from "firebase/firestore";
  const [userData, setUserData] = useState(false);

   const user_data = collection(db, "users");
  const q = query(user_data, where("user_id", "==", auth.currentUser.email));

  const querySnapshot = async () => {
    const snapshot = await getDocs(q);
    snapshot.forEach((doc) => {
      console.log(doc.data());
      setUserData(doc.data());
    });
  };

  React.useEffect(() => {
    querySnapshot();
  }, []);
```

그랬더니 해당 페이지에서 새로고침 시 빈화면이 보이고 
`TypeError: Cannot read properties of null (reading 'email')` 에러가 떴습니다.

게시물 수정 페이지에서는
아래와 같이 작성했습니다.

```
// ModifiA.js / ModifiB.js / ModifiC.js 공통사항

            {auth.currentUser !== null
              ? posting.user_id === auth.currentUser.email && (
                  <>
                    <ModifiBtn
                      onClick={() => {
                        modifiMagazine(magazine_id);
                        navigate("/");
                      }}
                    >
                      수정완료
                    </ModifiBtn>
                  </>
                )
              : null}
```

아무래도 새로고침 과정에서 `auth.currentUser` 값이 null 이 되는 순간에 에러가 뜨는 것 같아서
위 코드처럼 null이 아닐 경우에만 명령이 실행되도록 했지만 마찬가지로 새로고침 시 빈화면이 뜹니다.

이 문제를 해결하려고 많은 시간을 보냈으나 이 문제는 결국 시간 안에 해결하지 못해서 도움을 청합니다.

어떤 방법이 좋을지 의견 주시면 감사하겠습니다!

**Comment by jihyunan-dev** [comment]
먼저 `auth.currentUser`는 항상 있는 값인가요? 그게 `null`이라도?
`console.log(auth)`를 해서 currentUser는 항상 존재하는 property인지 확인하신 후, currentUser가 존재하지 않는 경우가 있다면 그 부분까지 처리를 해주셔야 할 것 같아요:)

만약 그렇지 않다면 다른 문제의 에러일 수도 있으니 에러메시지가 다른 경우에는 추가로 보여주시면 좋겠습니다:)
